import theme from '@/styles/theme';

export const pubCategory = [
  { name: '전체', engName: 'all', page: 'ALL', textColor: theme.colors.white, backgroundColor: '#FFFFFF1A' },
  {
    name: '자전',
    engName: 'freeMajor',
    page: 'B',
    textColor: theme.colors.pink,
    backgroundColor: '#FF89D733',
    image: '/img/pubSectionB.png',
  },
  {
    name: '경영',
    engName: 'business',
    page: 'A',
    textColor: theme.colors.green,
    backgroundColor: '#42CF6133',
    image: '/img/pubSectionA.png',
  },
  {
    name: '미대',
    engName: 'fineArt',
    page: 'C',
    textColor: theme.colors.purple,
    backgroundColor: '#D291F033',
    image: '/img/pubSectionC.png',
  },
  {
    name: '경제',
    engName: 'economics',
    page: 'A',
    textColor: theme.colors.green,
    backgroundColor: '#42CF6133',
    image: '/img/pubSectionA.png',
  },
  {
    name: '건축도시',
    engName: 'architecture',
    page: 'C',
    textColor: theme.colors.purple,
    backgroundColor: '#D291F033',
    image: '/img/pubSectionC.png',
  },
  {
    name: '디경융',
    engName: 'designBusiness',
    page: 'B',
    textColor: theme.colors.pink,
    backgroundColor: '#FF89D733',
    image: '/img/pubSectionB.png',
  },
  {
    name: '공연예술',
    engName: 'performingArts',
    page: 'B',
    textColor: theme.colors.pink,
    backgroundColor: '#FF89D733',
    image: '/img/pubSectionB.png',
  },
  {
    name: '사대',
    engName: 'education',
    page: 'A',
    textColor: theme.colors.green,
    backgroundColor: '#42CF6133',
    image: '/img/pubSectionA.png',
  },
  {
    name: '법대',
    engName: 'law',
    page: 'B',
    textColor: theme.colors.pink,
    backgroundColor: '#FF89D733',
    image: '/img/pubSectionB.png',
  },
  {
    name: '문대',
    engName: 'humanities',
    page: 'B',
    textColor: theme.colors.pink,
    backgroundColor: '#FF89D733',
    image: '/img/pubSectionB.png',
  },
  {
    name: '공대',
    engName: 'engineering',
    page: 'A',
    textColor: theme.colors.green,
    backgroundColor: '#42CF6133',
    image: '/img/pubSectionA.png',
  },
  {
    name: '총동아리연합회',
    engName: 'union',
    page: 'A',
    textColor: theme.colors.green,
    backgroundColor: '#42CF6133',
    image: '/img/pubSectionA.png',
  },
];
