export const pubCategory = [
  { name: '전체', engName: 'all', page: 'ALL' },
  { name: '자전', engName: 'freeMajor', page: 'B' },
  { name: '경영', engName: 'business', page: 'A' },
  { name: '미대', engName: 'fineArt', page: 'C' },
  { name: '경제', engName: 'economics', page: 'A' },
  { name: '건축', engName: 'architecture', page: 'C' },
  { name: '디경융', engName: 'designBusiness', page: 'B' },
  { name: '공연예술', engName: 'performingArts', page: 'B' },
  { name: '사대', engName: 'education', page: 'A' },
  { name: '법대', engName: 'law', page: 'B' },
  { name: '문대', engName: 'humanities', page: 'B' },
  { name: '공대', engName: 'engineering', page: 'A' },
  { name: '총동아리연합', engName: 'union', page: 'A' },
];
